web: &base
  image: hchinchilla/django-example
  ports:
   - 8080:8080
  volumes:
   - .:/code
  links:
   - db
  environment:
    MYSQL_WAIT_TIME: 0
  command: ["gunicorn", "django_example.wsgi:application", "-b", "0.0.0.0:8080", "--log-file=-", "--log-level=debug", "--reload"]

db:
  image: mariadb:latest
  ports:
   - 3306
  environment:
    MYSQL_ROOT_PASSWORD: super-secret
    MYSQL_DATABASE: project_example
    MYSQL_USER: project_example
    MYSQL_PASSWORD: qwerty
  volumes:
    - .data/db:/var/lib/mysql

## development utils
manage:
  <<: *base
  entrypoint: ["python", "manage.py"]
  command: "help"


# deploy tools
centurion:
  image: habitissimo/centurion:latest
  volumes:
    - ".:/code"
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "~/.dockercfg:/root/.dockercfg"
    - "~/.docker:/root/.docker"
