web:
  image: hchinchilla/nginx-django-example
  ports:
    - 80:80
  volumes:
    - config/nginx/nginx.conf:/etc/nginx/nginx.conf.tpl
  links:
    - gunicorn

gunicorn: &base
  image: hchinchilla/django-example
  ports:
   - 8080:8080
  volumes:
   - .:/code
  links:
   - db
  environment:
    DB_WAIT_TIME: 2
  command: ["gunicorn", "django_example.wsgi:application", "-b", "0.0.0.0:8080", "--log-file=-", "--log-level=debug", "--reload"]

db:
  image: postgres:9.4.1
  environment:
    - "POSTGRES_USER=postgresql"
    - "POSTGRES_PASSWORD=supersecret"
  expose:
    - "5432"
  volumes:
    - "/opt/data/postgres:/var/lib/postgresql/data"

## development utils
manage:
  <<: *base
  entrypoint: ["python", "manage.py"]
  command: "help"

# deploy tools
centurion:
  image: habitissimo/centurion:latest
  volumes:
    - ".:/code"
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "~/.dockercfg:/root/.dockercfg"
    - "~/.docker:/root/.docker"
